
import type { Exam } from './exam-data';

export const mpscRajyasevaExam: Exam = {
  id: 'mpsc-rajyaseva',
  title: 'MPSC Rajyaseva Exam',
  description: 'A comprehensive overview of the MPSC Rajyaseva (State Services) Examination, based on the revised pattern from 2023 onwards.',
  stages: [
    {
      title: 'Stage I: Preliminary Examination',
      description: 'An objective-type screening test. Marks are not counted for the final merit list, but candidates must clear the cut-off. The CSAT paper is qualifying in nature.',
      papers: [
        {
          name: 'Paper I',
          subject: 'General Studies (GS)',
          duration: '2 hours',
          marks: 200,
          nature: 'Merit',
          syllabus: [
            '**1. Current Affairs (सामायिक घडामोडी)**: State, national, and international current events, Government schemes (state + central), Important reports and indices (NITI Aayog, UN, World Bank), Awards, sports, science-tech, personalities in news.',
            '**2. History of India and Maharashtra (इतिहास)**: Ancient and Medieval India, Modern Indian History, History of Maharashtra (Shivaji, Maratha Empire, role in freedom struggle, Social reformers).',
            '**3. Geography of India and Maharashtra (भूगोल)**: Physical, Economic, and Human Geography. Maharashtra-specific rivers, soils, dams, transport, and environmental issues.',
            '**4. Indian Polity and Governance (राज्यशास्त्र)**: Indian Constitution, Union and State governments, Judiciary, Local governance (Panchayati Raj), RTI Act, Social justice.',
            '**5. Economy and Planning (अर्थव्यवस्था)**: Indian economy sectors, GDP, NITI Aayog, Budget, Banking, Inflation, Poverty, and Maharashtra’s economy.',
            '**6. General Science and Technology (सामान्य विज्ञान)**: Basic Physics, Chemistry, Biology; Biotechnology, nanotechnology; Everyday science (health, diseases).',
            '**7. Environment and Ecology (पर्यावरणशास्त्र)**: Ecosystems, biodiversity, climate change, conservation, and environmental movements in Maharashtra.',
            '**8. Maharashtra-specific Topics**: State administration, development programs, historical and cultural heritage, and basic awareness of Marathi language.',
          ],
        },
        {
          name: 'Paper II',
          subject: 'CSAT (Aptitude Test)',
          duration: '2 hours',
          marks: 200,
          qualifyingMarks: '33%',
          nature: 'Qualifying',
          syllabus: [
            '**1. Comprehension (वाचन समज)**: Reading passages (English and Marathi) with fact-based and inference-based questions.',
            '**2. Interpersonal Skills including Communication**: Situation-based questions testing clarity and empathy.',
            '**3. Logical Reasoning and Analytical Ability**: Syllogisms, statement-conclusion, cause-effect reasoning, and problem-solving.',
            '**4. General Mental Ability**: Number series, coding-decoding, blood relations, directions, rankings.',
            '**5. Basic Numeracy (up to Class X)**: Arithmetic, simple & compound interest, time-speed-distance, data interpretation.',
          ],
        },
      ],
      notes: [
          'Both papers are in English & Marathi.'
      ]
    },
    {
      title: 'Stage II: Main Examination',
      description: 'The Main Exam is descriptive in nature. Marks from the qualifying paper are not counted, while marks from the Essay and 4 GS papers are counted for the final ranking.',
      papers: [
        { 
            name: 'Qualifying Paper', 
            subject: 'Marathi & English Language', 
            duration: '3 hours', 
            marks: 100, 
            qualifyingMarks: '35% overall', 
            nature: 'Qualifying',
            syllabus: [
                '**A. Marathi (50 marks)**',
                'Essay Writing (15 marks)',
                'Translation from English to Marathi (10 marks)',
                'Precis Writing (10 marks)',
                'Grammar (15 marks)',
                '**B. English (50 marks)**',
                'Essay Writing (15 marks)',
                'Translation from Marathi to English (10 marks)',
                'Precis Writing (10 marks)',
                'Grammar (15 marks)',
            ]
        },
        { 
            name: 'Paper I', 
            subject: 'Essay', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**Structure**',
                'Three essays need to be written.',
                'Topics are generally drawn from: Contemporary issues, Ethics, governance, Economic/developmental issues, Science and technology, Environment, Philosophy, History/society/culture (including Maharashtra-specific angles).',
                '**Instructions**',
                'Each essay is typically expected to be between 1000–1200 words.',
                'Essays should demonstrate: Clarity of thought, Logical flow, Coherence, Originality, Depth of analysis, and Balanced viewpoints.',
                '**Tips**',
                'Structure your essay into: Introduction, Body, and Conclusion.',
                'Use facts, real-world examples (esp. Maharashtra), quotes, and balanced arguments.',
                'Avoid taking extreme or biased positions.',
            ]
        },
        { 
            name: 'Paper II', 
            subject: 'General Studies I (History, Geography, Society)', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**A. History and Culture**',
                'Ancient and Medieval Indian History',
                'Modern Indian History (1757–1947)',
                'Social reform movements (India & Maharashtra)',
                'Post-independence consolidation',
                'History of Maharashtra: Shivaji, Marathas, freedom struggle',
                'Art, Culture, Literature, Architecture',
                '**B. Geography**',
                'Physical Geography of India and Maharashtra',
                'Climate, resources, rivers, soils, natural hazards',
                'Economic Geography: agriculture, industries, trade',
                'Human Geography: population, urbanization, migration',
                'Environmental geography, biodiversity, disaster management',
                '**C. Society**',
                'Indian society: features, diversity, secularism',
                'Caste, religion, language, ethnicity',
                'Social problems: poverty, unemployment, communalism',
                'Social justice and welfare schemes',
                'Role of women and gender issues',
                'Regionalism and communalism',
            ]
        },
        { 
            name: 'Paper III', 
            subject: 'General Studies II (Polity, Law, Governance)', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**A. Indian Constitution and Polity**',
                'Historical Background: Making of the Constitution',
                'Salient Features, Preamble, Fundamental Rights, DPSPs, Fundamental Duties',
                'Union and State Government: Executive, Legislature, Judiciary',
                'Federal Structure and Centre-State Relations',
                'Constitutional and Statutory Bodies: EC, UPSC, CAG, etc.',
                '**B. Governance and Public Policy**',
                'Good Governance, E-Governance, RTI',
                'Citizen Charters, Transparency, Accountability',
                'Role of Civil Services in Democracy',
                'Government Policies and Interventions (especially in Maharashtra)',
                '**C. Social Justice and Welfare**',
                'Welfare schemes for: SCs, STs, OBCs, minorities, women, etc.',
                'Constitutional Provisions and Policies',
                'Issues of Social Inclusion and Empowerment',
                '**D. Law and Public Policy**',
                'Important Acts/Laws related to: Women, Child, Environment, Cybersecurity, etc.',
                'Right to Education, Right to Food, Right to Health',
                'Disaster Laws and Administrative Responses',
                '**E. International Relations**',
                'India’s foreign policy: objectives, principles',
                'India and neighbors: SAARC, ASEAN',
                'International institutions: UN, WTO, IMF, World Bank',
                'Bilateral and Multilateral relations with major powers',
            ]
        },
        { 
            name: 'Paper IV', 
            subject: 'General Studies III (Economy, S&T, Security)', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**A. Indian Economy and Planning**',
                'Growth, Development, Sustainable Development, Poverty, Unemployment',
                'Planning: NITI Aayog; Fiscal Policy: Budgeting, GST; Monetary Policy: RBI, Inflation',
                'Economy of Maharashtra: Growth, Issues, State Finances',
                '**B. Agriculture and Allied Sectors**',
                'Land reforms, Irrigation, Cropping patterns, Farm Mechanization',
                'Agricultural Marketing (APMC, e-NAM), Food Processing',
                'Agricultural credit and insurance (PMFBY, KCC)',
                '**C. Industry and Infrastructure**',
                'Industrial Policy, MSMEs, Startups, Make in India',
                'Infrastructure: Roads, Railways, Ports, Energy, Smart Cities, PPP Models',
                '**D. Science and Technology**',
                'Role in India’s development: Space, Nuclear, Biotech, Nanotech, Robotics, AI',
                'ICT: Digital India, Cybersecurity',
                '**E. Environment and Ecology**',
                'Conservation, Pollution, Climate Change, Waste Management, EIA, SDGs',
                'Forest and Wildlife Conservation (incl. in Maharashtra)',
                '**F. Internal Security and Disaster Management**',
                'Threats from Extremism, Terrorism, Cybercrime, Organized crime',
                'Role of Security Forces, Cybersecurity, Money laundering',
                'Disaster Management: Preparedness, Response, Role of NDMA/SDRF',
            ]
        },
        { 
            name: 'Paper V', 
            subject: 'General Studies IV (Ethics, Integrity, Aptitude)', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**A. Ethics and Human Interface**',
                'Essence, Determinants, and Consequences of Ethics; Human Values from leaders',
                '**B. Attitude**',
                'Content, Structure, Function; Moral and Political Attitudes; Social Influence',
                '**C. Aptitude and Foundational Values for Civil Services**',
                'Integrity, Impartiality, Objectivity, Dedication, Empathy, Compassion',
                '**D. Emotional Intelligence**',
                'Concepts, Dimensions, and Application in Administration',
                '**E. Contributions of Thinkers and Philosophers**',
                'Indian and Western moral thinkers and their application in governance',
                '**F. Public/Civil Service Values and Ethics in Public Administration**',
                'Ethical Concerns, Dilemmas, Accountability, Ethical Governance',
                '**G. Probity in Governance**',
                'Concept of Public Service, RTI, Codes of Ethics/Conduct, Citizen’s Charters, Corruption',
                '**H. Case Studies on Above Topics**',
                'Testing ethical reasoning, moral compass, and decision-making in practical situations',
            ]
        },
      ],
      notes: [
          'No Optional Subjects in the revised MPSC pattern (2023 onwards).',
          'Medium of papers is Marathi or English (except for language sections).'
      ],
    },
    {
      title: 'Stage III: Interview / Personality Test',
      description: 'A personality test for candidates who clear the Main Examination, assessing their suitability for a career in public administration.',
      papers: [
          { name: 'Interview', subject: 'Personality Test', marks: 100, nature: 'Merit' }
      ]
    },
  ],
  finalScore: [
    { component: 'Mains (Essay + 4 GS Papers)', marks: 1250 },
    { component: 'Interview', marks: 100 },
  ],
};
