
import type { Exam } from './exam-data';

export const mpscRajyasevaExam: Exam = {
  id: 'mpsc-rajyaseva',
  title: 'MPSC Rajyaseva Exam',
  description: 'A comprehensive overview of the MPSC Rajyaseva (State Services) Examination, based on the revised pattern from 2023 onwards.',
  stages: [
    {
      title: 'Stage I: Preliminary Examination',
      description: 'An objective-type screening test. Marks are not counted for the final merit list, but candidates must clear the cut-off. The CSAT paper is qualifying in nature.',
      papers: [
        {
          name: 'Paper I',
          subject: 'General Studies (GS)',
          duration: '2 hours',
          marks: 200,
          nature: 'Merit',
          syllabus: [
            '**1. Current Affairs (सामायिक घडामोडी)**',
            'State, national, and international current events',
            'Government schemes (state + central)',
            'Important reports and indices (NITI Aayog, UN, World Bank)',
            'Awards, sports, science-tech, personalities in news',
            '**2. History of India and Maharashtra (इतिहास)**',
            '**a. Ancient and Medieval India**',
            'Vedic period, Mauryan and Gupta empires',
            'Bhakti and Sufi movements',
            'Sultanate and Mughal administration',
            '**b. Modern Indian History**',
            'British rule: policies and impact',
            'Social reform movements',
            '1857 revolt and freedom movements (1885–1947)',
            'Mahatma Gandhi, Nehru, Ambedkar, Tilak, Savarkar',
            '**c. History of Maharashtra**',
            'Shivaji and Maratha Empire',
            'Maharashtra’s role in 1857 and freedom struggle',
            'Samyukta Maharashtra Movement',
            'Social reformers: Phule, Shahu, Ambedkar',
            '**3. Geography of India and Maharashtra (भूगोल)**',
            '**a. Physical Geography**',
            'Himalayas, rivers, climate, soils',
            '**b. Economic Geography**',
            'agriculture, minerals, industries',
            '**c. Human Geography**',
            'population, migration, urbanization',
            '**d. Geography of Maharashtra**',
            'Rivers (Godavari, Krishna, Tapi)',
            'Soil types (Black Cotton, Laterite, etc.)',
            'Dams and irrigation',
            'Transport and trade',
            'Environmental issues',
            '**4. Indian Polity and Governance (राज्यशास्त्र)**',
            '**a. Indian Constitution**',
            'features, amendments, Preamble',
            'Fundamental Rights and Duties, DPSPs',
            '**b. Governance Structure**',
            'Union and State governments',
            'Parliament and State Legislature',
            'Judiciary system',
            '**c. Institutions**',
            'Election Commission, CAG, UPSC, MPSC',
            '**d. Local Governance & Acts**',
            '73rd & 74th Amendments, Panchayati Raj',
            'RTI Act, Disaster Management Act',
            '**e. Social Justice**',
            'SC/ST/OBC/Minority issues',
            '**5. Economy and Planning (अर्थव्यवस्था)**',
            '**a. Core Concepts**',
            'Indian economy: sectors and structure',
            'GDP, national income concepts',
            'Poverty, unemployment, inflation',
            '**b. Planning and Policy**',
            'Planning: NITI Aayog, 5-Year Plans (older)',
            'Budget, taxation, fiscal deficit',
            'Banking and financial institutions',
            '**c. Sectors**',
            'Agriculture and allied sectors',
            'Industries and infrastructure',
            '**d. Maharashtra Economy**',
            'Maharashtra’s economy: sectors, development indicators',
            '**6. General Science and Technology (सामान्य विज्ञान)**',
            '**a. Basic Sciences**',
            'Physics, Chemistry, Biology (basic school-level)',
            '**b. Applied Science**',
            'Biotechnology, nanotechnology (basic concepts)',
            'Space and nuclear technology in India',
            '**c. Health**',
            'Everyday science: nutrition, health, diseases, vaccines',
            '**d. S&T and Environment**',
            'Science and environment: pollution, conservation',
            '**7. Environment and Ecology (पर्यावरणशास्त्र)**',
            '**a. Core Concepts**',
            'Ecosystems, biodiversity, conservation',
            '**b. Climate Change**',
            'causes, effects, global conventions',
            'National Action Plan on Climate Change',
            '**c. Maharashtra Environment**',
            'Forest types, wildlife sanctuaries in Maharashtra',
            'Environmental movements in Maharashtra',
            '**d. Sustainable Development**',
            'Sustainable development and SDGs',
            '**8. Maharashtra-specific Topics**',
            'State administration and policy',
            'Development programs and initiatives',
            'Historical and cultural heritage',
            'Marathi language and literature (basic awareness)',
          ],
        },
        {
          name: 'Paper II',
          subject: 'CSAT (Aptitude Test)',
          duration: '2 hours',
          marks: 200,
          qualifyingMarks: '33%',
          nature: 'Qualifying',
          syllabus: [
            '**1. Comprehension (वाचन समज)**',
            'Reading passages (English and Marathi)',
            'Fact-based and inference-based questions',
            '**2. Interpersonal Skills including Communication**',
            'Situation-based questions',
            'Clarity of communication and empathy',
            '**3. Logical Reasoning and Analytical Ability**',
            'Syllogisms, statement-conclusion',
            'Cause-effect reasoning',
            'Decision-making and problem-solving',
            '**4. General Mental Ability**',
            'Number series, coding-decoding',
            'Blood relations, directions, rankings',
            '**5. Basic Numeracy (up to Class X)**',
            'Arithmetic: percentages, profit & loss, averages',
            'Simple & compound interest',
            'Time-speed-distance, time-work',
            'Data interpretation: graphs, charts, tables',
          ],
        },
      ],
      notes: [
          'Both papers are in English & Marathi.'
      ]
    },
    {
      title: 'Stage II: Main Examination',
      description: 'The Main Exam is descriptive in nature. Marks from the qualifying paper are not counted, while marks from the Essay and 4 GS papers are counted for the final ranking.',
      papers: [
        { 
            name: 'Qualifying Paper', 
            subject: 'Marathi & English Language', 
            duration: '3 hours', 
            marks: 100, 
            qualifyingMarks: '35% overall', 
            nature: 'Qualifying',
            syllabus: [
                '**A. Marathi (50 marks)**',
                'Essay Writing (15 marks)',
                'Translation from English to Marathi (10 marks)',
                'Precis Writing (10 marks)',
                'Grammar (15 marks)',
                '**B. English (50 marks)**',
                'Essay Writing (15 marks)',
                'Translation from Marathi to English (10 marks)',
                'Precis Writing (10 marks)',
                'Grammar (15 marks)',
            ]
        },
        { 
            name: 'Paper I', 
            subject: 'Essay', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**Structure**',
                'Three essays need to be written.',
                'Topics are generally drawn from: Contemporary issues (national/international), Ethics, governance, and social justice, Economic and developmental issues, Science and technology, Environment and sustainable development, Philosophy and abstract themes, History, society, and culture (including Maharashtra-specific angles)',
                '**Instructions**',
                'Each essay is typically expected to be between 1000–1200 words.',
                'Topics are provided in English and Marathi, and candidates can write in their chosen medium.',
                'Essays should demonstrate: Clarity of thought, Logical flow, Coherence and structure, Originality, Depth of analysis, and Balanced viewpoints.',
                '**Past Examples of Themes**',
                'Ethical/Social: “Is development at the cost of the environment justifiable?” or “Role of youth in combating corruption.”',
                'Philosophical: “Happiness is a journey, not a destination.” or “Technology shapes society more than society shapes technology.”',
                'Economic/Political: “Federalism in India: Challenges and Prospects.” or “Digital India and its socio-economic implications.”',
                'Maharashtra-specific: “Urbanization in Maharashtra: Boon or Bane?” or “Role of cooperatives in Maharashtra’s development.”',
                '**Tips**',
                'Structure your essay into: Introduction, Body (with subheadings or thematic paragraphs), Conclusion (with a future-forward tone)',
                'Use facts, real-world examples (esp. Maharashtra), quotes, and balanced arguments.',
                'Avoid taking extreme or biased positions.',
            ]
        },
        { 
            name: 'Paper II', 
            subject: 'General Studies I (History, Geography, Society)', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**A. History and Culture**',
                'Ancient and Medieval Indian History',
                'Modern Indian History (1757–1947)',
                'Social reform movements (India & Maharashtra)',
                'Post-independence consolidation',
                'History of Maharashtra: Shivaji, Marathas, freedom struggle',
                'Art, Culture, Literature, Architecture',
                '**B. Geography**',
                'Physical Geography of India and Maharashtra',
                'Climate, resources, rivers, soils, natural hazards',
                'Economic Geography: agriculture, industries, trade',
                'Human Geography: population, urbanization, migration',
                'Environmental geography, biodiversity, disaster management',
                '**C. Society**',
                'Indian society: features, diversity, secularism',
                'Caste, religion, language, ethnicity',
                'Social problems: poverty, unemployment, communalism',
                'Social justice and welfare schemes',
                'Role of women and gender issues',
                'Regionalism and communalism',
            ]
        },
        { 
            name: 'Paper III', 
            subject: 'General Studies II (Constitution, Polity, Governance, Law, Social Justice, and International Relations)', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**A. Indian Constitution and Polity**',
                'Historical Background: Making of the Constitution',
                'Salient Features of the Constitution',
                'Preamble, Fundamental Rights, Directive Principles, Fundamental Duties',
                'Union and State Government: Executive, PM, Council of Ministers, Governor, CM; Legislature: Parliament and State Legislatures; Judiciary: Supreme Court, High Courts, Subordinate Judiciary',
                'Federal Structure and Centre-State Relations',
                'Constitutional and Statutory Bodies: Election Commission, UPSC, CAG, Finance Commission, NITI Aayog, Human Rights Commission, SC/ST Commission, Women’s Commission, etc.',
                '**B. Governance and Public Policy**',
                'Good Governance, E-Governance, RTI',
                'Citizen Charters, Transparency, Accountability',
                'Role of Civil Services in Democracy',
                'Governance Reforms and Administrative Reforms',
                'Social Audit, Vigilance Mechanisms',
                'Use of ICT in administration',
                'Government Policies and Interventions for Development (especially in Maharashtra)',
                'Issues related to implementation of schemes',
                '**C. Social Justice and Welfare**',
                'Welfare schemes for: SCs, STs, OBCs, minorities, women, children, elderly, disabled',
                'Constitutional Provisions and Policies',
                'Issues of Social Inclusion, Empowerment',
                'Problems of Vulnerable Sections',
                '**D. Law and Public Policy**',
                'Legal Awareness',
                'Important Acts/Laws related to: Women and Child Welfare, Environment and Forests, Education and Health, Cybersecurity and IT',
                'Right to Education, Right to Food, Right to Health',
                'Disaster Laws and Administrative Responses',
                '**E. International Relations**',
                'India’s foreign policy: objectives, principles',
                'India and neighbors: SAARC, ASEAN',
                'International institutions: UN, WTO, IMF, World Bank',
                'Bilateral and Multilateral relations with: USA, Russia, China, EU, Japan, West Asia',
                'Role of India in global governance',
                'Agreements and Treaties impacting India',
            ]
        },
        { 
            name: 'Paper IV', 
            subject: 'General Studies III (Indian Economy, Agriculture, Science, Technology, Environment, and Internal Security)', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**A. Indian Economy and Planning**',
                'Nature and characteristics of the Indian Economy',
                'Growth, Development, and Sustainable Development',
                'Poverty, Unemployment, and Inequality',
                'Planning: Five Year Plans, NITI Aayog',
                'Economic Reforms: LPG Model',
                'Fiscal Policy: Budgeting, Deficits, Taxation (GST)',
                'Monetary Policy: RBI, Inflation, Banking, NBFCs',
                'Public Distribution System',
                'Government Welfare Schemes (esp. Maharashtra)',
                'Economy of Maharashtra: Growth, Issues, State Finances',
                '**B. Agriculture and Allied Sectors**',
                'Land reforms, Irrigation, Cropping patterns',
                'Farm Mechanization, Agri-Infrastructure',
                'Agricultural Marketing, APMC Act, e-NAM',
                'Animal Husbandry, Poultry, Fishery, Sericulture',
                'Food Processing and Agri-Industries',
                'Government schemes for farmers',
                'Agricultural credit and insurance (PMFBY, KCC)',
                'Organic and Natural Farming',
                'Role of biotechnology in agriculture',
                '**C. Industry and Infrastructure**',
                'Industrial Policy and Growth Trends',
                'MSMEs, Startups, Make in India, Skill India',
                'Industrial corridors, SEZs',
                'Infrastructure: Roads, Railways, Ports, Energy, Smart Cities',
                'Public-Private Partnership (PPP) Models',
                'FDI and Industrial Investment Trends',
                '**D. Science and Technology**',
                'Role of S&T in India’s development',
                'Space Technology: ISRO, satellites, Gaganyaan',
                'Nuclear Technology',
                'Biotechnology: GM crops, Genetic engineering',
                'Nanotechnology, Robotics',
                'ICT: Digital India, Cybersecurity',
                'Artificial Intelligence, Machine Learning',
                'Indigenous innovation and R&D policy',
                'Technology Missions in agriculture, water, health',
                '**E. Environment and Ecology**',
                'Environmental Conservation and Legislation',
                'Biodiversity and Climate Change',
                'Forest and Wildlife Conservation (incl. in Maharashtra)',
                'Pollution and Control Measures',
                'National Action Plan on Climate Change',
                'UN Frameworks and COP Summits',
                'Waste Management: Solid, e-waste, biomedical',
                'Environmental Impact Assessment (EIA)',
                'Sustainable Development Goals (SDGs)',
                '**F. Internal Security and Disaster Management**',
                'Internal Security: Threats from Extremism, Terrorism, Cybercrime',
                'Role of Armed Forces, CAPFs, Police, Intelligence',
                'Cybersecurity and Information Warfare',
                'Money laundering, Fake currency, Organized crime',
                'Disaster Management: Types, Preparedness, Response',
                'Role of NDMA, SDRF, Local Administration',
                'Community-based disaster risk reduction',
            ]
        },
        { 
            name: 'Paper V', 
            subject: 'General Studies IV (Ethics, Integrity, and Aptitude)', 
            duration: '3 hours', 
            marks: 250, 
            nature: 'Merit',
            syllabus: [
                '**A. Ethics and Human Interface**',
                'Essence of Ethics, Determinants and Consequences of Ethics in Human Action',
                'Dimensions of Ethics',
                'Ethics in Private and Public Relationships',
                'Human Values: Lessons from the lives and teachings of great leaders, reformers, and administrators',
                'Role of family, society, and educational institutions in inculcating values',
                '**B. Attitude**',
                'Content, Structure, and Function of Attitude',
                'Influence and Relation with Thought and Behaviour',
                'Moral and Political Attitudes',
                'Social Influence and Persuasion',
                '**C. Aptitude and Foundational Values for Civil Services**',
                'Integrity, Impartiality, and Non-partisanship',
                'Objectivity, Dedication to Public Service',
                'Empathy, Tolerance, and Compassion towards the weaker sections',
                '**D. Emotional Intelligence**',
                'Concepts and Dimensions of Emotional Intelligence',
                'Emotional Intelligence in Personal and Professional Life',
                'Role of Emotional Intelligence in Decision-Making and Leadership',
                '**E. Contributions of Thinkers and Philosophers**',
                'Contributions of Indian and Western moral thinkers and philosophers',
                'Application of their ideas in administration and governance',
                '**F. Public/Civil Service Values and Ethics in Public Administration**',
                'Status and Problems of Civil Services',
                'Ethical Concerns and Dilemmas in Government and Private Institutions',
                'Laws, Rules, Regulations, and Conscience as Sources of Ethical Guidance',
                'Accountability and Ethical Governance',
                'Strengthening of Ethical and Moral Values in Governance',
                'Ethical Issues in International Relations and Funding',
                '**G. Probity in Governance**',
                'Concept of Public Service, Philosophical Basis of Governance and Probity',
                'Information Sharing and Transparency in Government',
                'Right to Information (RTI)',
                'Codes of Ethics, Codes of Conduct',
                'Citizen’s Charters',
                'Work Culture',
                'Quality of Service Delivery',
                'Utilization of Public Funds',
                'Challenges of Corruption',
                '**H. Case Studies on Above Topics**',
                'Practical situations involving: Decision making, Ethical dilemmas, Conflict resolution, Administrative behavior',
                'Testing candidate’s: Ethical reasoning, Moral compass, Application of values to real-world scenarios',
            ]
        },
      ],
      notes: [
          'No Optional Subjects in the revised MPSC pattern (2023 onwards).',
          'Medium of papers is Marathi or English (except for language sections).'
      ],
    },
    {
      title: 'Stage III: Interview / Personality Test',
      description: 'A personality test for candidates who clear the Main Examination, assessing their suitability for a career in public administration.',
      papers: [
          { name: 'Interview', subject: 'Personality Test', marks: 100, nature: 'Merit' }
      ]
    },
  ],
  finalScore: [
    { component: 'Mains (Essay + 4 GS Papers)', marks: 1250 },
    { component: 'Interview', marks: 100 },
  ],
};
