
import type { SyllabusTopic } from '@/lib/types';

export const initialSyllabusData: SyllabusTopic[] = [
  {
    id: 'preliminary-exam',
    title: 'Stage I: Preliminary Examination',
    icon: 'ClipboardList',
    description: 'This stage consists of two compulsory objective-type papers. Paper I (GS) determines the cut-off, while Paper II (CSAT) is qualifying (33%). There is negative marking for incorrect answers.',
    tags: ['objective', 'qualifying'],
    mastery: 'none',
    resources: [],
    subtopics: [
      {
        id: 'prelims-gs1',
        title: 'Paper I: General Studies (GS)',
        icon: 'FileText',
        description: 'Decides the cut-off for the Main exam. Syllabus covers a wide range of subjects from current events to general science. Marks: 200, Questions: 100.',
        tags: ['gs', 'merit-cutoff'],
        mastery: 'none',
        resources: [],
        subtopics: [
          {
            id: 'prelims-gs1-current-events',
            title: 'Current events of national and international importance',
            description: 'Current events of national and international importance, covering polity, economy, environment, science & tech, and international relations.',
            tags: ['dynamic', 'high-priority'],
            mastery: 'none',
            resources: [],
          },
          {
            id: 'prelims-gs1-history',
            title: 'History of India and Indian National Movement',
            description: 'Covers Ancient, Medieval, and Modern Indian history, with a special focus on the national freedom struggle.',
            tags: ['history', 'static'],
            mastery: 'none',
            resources: [],
          },
          {
            id: 'prelims-gs1-geography',
            title: 'Indian and World Geography',
            description: 'Physical, Social, and Economic Geography of India and the World.',
            tags: ['geography', 'static'],
            mastery: 'none',
            resources: [],
            subtopics: [
                { id: 'prelims-geography-physical', title: 'Physical Geography', description: 'Covers key concepts of world physical geography.', tags: [], mastery: 'none', resources: [] },
                { id: 'prelims-geography-social', title: 'Social Geography', description: 'Covers key concepts of social geography of India and the world.', tags: [], mastery: 'none', resources: [] },
                { id: 'prelims-geography-economic', title: 'Economic Geography', description: 'Covers key concepts of economic geography of India and the world.', tags: [], mastery: 'none', resources: [] },
            ]
          },
          {
            id: 'prelims-gs1-polity',
            title: 'Indian Polity and Governance',
            description: 'Constitution, Political System, Panchayati Raj, Public Policy, Rights Issues, etc.',
            tags: ['polity', 'governance'],
            mastery: 'none',
            resources: [],
            subtopics: [
                { id: 'upsc-polity-constitution', title: 'Constitution', description: 'The foundational law and principles of the country.', tags: [], mastery: 'none', resources: [] },
                { id: 'upsc-polity-system', title: 'Political System', description: 'The structure and functioning of the government.', tags: [], mastery: 'none', resources: [] },
                { id: 'upsc-polity-panchayati-raj', title: 'Panchayati Raj', description: 'Local self-governance system in rural India.', tags: [], mastery: 'none', resources: [] },
                { id: 'upsc-polity-public-policy', title: 'Public Policy', description: 'The principles upon which social laws are based.', tags: [], mastery: 'none', resources: [] },
                { id: 'upsc-polity-rights-issues', title: 'Rights Issues', description: 'Issues related to fundamental and other rights of citizens.', tags: [], mastery: 'none', resources: [] },
            ]
          },
          {
            id: 'prelims-gs1-economy',
            title: 'Economic and Social Development',
            description: 'Sustainable Development, Poverty, Inclusion, Demographics, Social Sector initiatives, etc.',
            tags: ['economy', 'development'],
            mastery: 'none',
            resources: [],
            subtopics: [
                { id: 'upsc-eco-sustainable-dev', title: 'Sustainable Development', description: 'Development that meets present needs without compromising future generations.', tags: [], mastery: 'none', resources: [] },
                { id: 'upsc-eco-poverty', title: 'Poverty', description: 'Issues and policies related to poverty alleviation.', tags: [], mastery: 'none', resources: [] },
                { id: 'upsc-eco-inclusion', title: 'Inclusion', description: 'Ensuring that all segments of society participate in and benefit from development.', tags: [], mastery: 'none', resources: [] },
                { id: 'upsc-eco-demographics', title: 'Demographics', description: 'The study of population dynamics.', tags: [], mastery: 'none', resources: [] },
                { id: 'upsc-eco-social-sector', title: 'Social Sector Initiatives', description: 'Government schemes and programs in health, education, etc.', tags: [], mastery: 'none', resources: [] },
            ]
          },
          {
            id: 'prelims-gs1-environment',
            title: 'Environment & Ecology',
            description: 'General issues on Environmental Ecology, Biodiversity, and Climate Change that do not require subject specialization.',
            tags: ['environment', 'ecology'],
            mastery: 'none',
            resources: [],
          },
          {
            id: 'prelims-gs1-science',
            title: 'General Science',
            description: 'Basics of Physics, Chemistry, Biology (up to Class X level) and key developments in S&T.',
            tags: ['science', 'technology'],
            mastery: 'none',
            resources: [],
          },
        ],
      },
      {
        id: 'prelims-csat',
        title: 'Paper II: CSAT (Civil Services Aptitude Test)',
        icon: 'FileText',
        description: 'A qualifying paper requiring 33% marks (66/200). Tests aptitude and reasoning skills. Marks: 200, Questions: 80.',
        tags: ['csat', 'aptitude', 'qualifying'],
        mastery: 'none',
        resources: [],
        subtopics: [
            { id: 'prelims-csat-comprehension', title: 'Comprehension', description: 'Reading passages with factual and inference-based questions.', tags: [], mastery: 'none', resources: [] },
            { id: 'prelims-csat-interpersonal', title: 'Interpersonal skills including communication skills', description: 'Testing the ability to interact effectively with others.', tags: [], mastery: 'none', resources: [] },
            { id: 'prelims-csat-reasoning', title: 'Logical reasoning and analytical ability', description: 'Syllogisms, blood relations, puzzles, seating arrangements.', tags: [], mastery: 'none', resources: [] },
            { id: 'prelims-csat-decision-making', title: 'Decision-making and problem-solving', description: 'Questions on ethical dilemmas and practical problem-solving. No negative marking for these.', tags: [], mastery: 'none', resources: [] },
            { id: 'prelims-csat-mental-ability', title: 'General mental ability', description: 'Testing reasoning and thinking ability.', tags: [], mastery: 'none', resources: [] },
            { id: 'prelims-csat-numeracy', title: 'Basic numeracy (Class X level)', description: 'Number systems, percentages, time & work, averages.', tags: [], mastery: 'none', resources: [] },
            { id: 'prelims-csat-di', title: 'Data interpretation (Class X level)', description: 'Interpreting charts, graphs, and tables.', tags: [], mastery: 'none', resources: [] },
        ]
      },
    ],
  },
  {
    id: 'main-exam',
    title: 'Stage II: Main Examination',
    icon: 'PencilLine',
    description: 'A descriptive exam consisting of 9 papers. Two papers are qualifying, and the other seven are counted for the final merit ranking. Total merit marks: 1750.',
    tags: ['descriptive', 'merit-based'],
    mastery: 'none',
    resources: [],
    subtopics: [
      {
        id: 'mains-qualifying',
        title: 'Qualifying Papers (A & B)',
        icon: 'ShieldCheck',
        description: 'These papers test basic language proficiency and are not counted for merit. Candidates must score at least 25% to pass.',
        tags: ['qualifying', 'language'],
        mastery: 'none',
        resources: [],
        subtopics: [
          {
            id: 'mains-qualifying-a',
            title: 'Paper A: Indian Language',
            description: 'Any language from the Eighth Schedule. The pattern is similar to the English paper, focusing on comprehension, précis, and translation.',
            tags: ['indian-language'],
            mastery: 'none',
            resources: [],
          },
          {
            id: 'mains-qualifying-b',
            title: 'Paper B: English',
            description: 'Tests comprehension of given passages, précis writing, usage and vocabulary, and short essays. Class X level.',
            tags: ['english'],
            mastery: 'none',
            resources: [],
          },
        ]
      },
      {
        id: 'mains-essay',
        title: 'Paper I: Essay',
        icon: 'FileText',
        description: 'Candidates write two essays on a variety of topics, testing their ability to organize ideas and write concisely. Marks: 250.',
        tags: ['essay', 'merit'],
        mastery: 'none',
        resources: [],
      },
      {
        id: 'mains-gs1',
        title: 'Paper II: General Studies I',
        icon: 'FileText',
        description: 'Indian Heritage and Culture, History and Geography of the World and Society. Marks: 250.',
        tags: ['gs-1', 'history', 'geography', 'society'],
        mastery: 'none',
        resources: [],
        subtopics: [
          { id: 'mains-gs1-art-culture', title: 'Indian Culture', description: 'Salient aspects of Art Forms, Literature, and Architecture from ancient to modern times.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs1-modern-history', title: 'Modern Indian History', description: 'From about the middle of the eighteenth century until the present- significant events, issues, personalities. The Freedom Struggle - its various stages and important contributors/contributions from different parts of the country. Post-independence consolidation and reorganization within the country.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs1-world-history', title: 'History of the World', description: 'Events from 18th century such as industrial revolution, world wars, redrawal of national boundaries, colonization, decolonization, political philosophies like communism, capitalism, socialism etc.— their forms and effect on the society.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs1-society', title: 'Society', description: 'Salient features of Indian Society, Diversity of India. Role of women and women’s organization, population and associated issues, poverty and developmental issues, urbanization, their problems and their remedies. Effects of globalization on Indian society. Social empowerment, communalism, regionalism & secularism.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs1-geography', title: 'Geography', description: 'Salient features of world’s physical geography. Distribution of key natural resources across the world (including South Asia and the Indian sub-continent); factors responsible for the location of primary, secondary, and tertiary sector industries in various parts of the world (including India). Important Geophysical phenomena such as earthquakes, Tsunami, Volcanic activity, cyclone etc., geographical features and their location-changes in critical geographical features (including water-bodies and ice-caps) and in flora and fauna and the effects of such changes.', tags: [], mastery: 'none', resources: [] },
        ],
      },
      {
        id: 'mains-gs2',
        title: 'Paper III: General Studies II',
        icon: 'FileText',
        description: 'Governance, Constitution, Polity, Social Justice and International relations. Marks: 250.',
        tags: ['gs-2', 'polity', 'governance', 'ir'],
        mastery: 'none',
        resources: [],
        subtopics: [
          { id: 'mains-gs2-constitution', title: 'Indian Constitution', description: 'Historical underpinnings, evolution, features, amendments, significant provisions and basic structure. Functions and responsibilities of the Union and the States, issues and challenges pertaining to the federal structure, devolution of powers and finances up to local levels and challenges therein. Separation of powers between various organs dispute redressal mechanisms and institutions. Comparison of the Indian constitutional scheme with that of other countries.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs2-polity', title: 'Polity', description: 'Parliament and State legislatures—structure, functioning, conduct of business, powers & privileges and issues arising out of these. Structure, organization and functioning of the Executive and the Judiciary—Ministries and Departments of the Government; pressure groups and formal/informal associations and their role in the Polity. Salient features of the Representation of People’s Act. Appointment to various Constitutional posts, powers, functions and responsibilities of various Constitutional Bodies. Statutory, regulatory and various quasi-judicial bodies.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs2-governance', title: 'Governance', description: 'Important aspects of governance, transparency and accountability, e-governance- applications, models, successes, limitations, and potential; citizens charters, transparency & accountability and institutional and other measures. Role of civil services in a democracy.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs2-social-justice', title: 'Social Justice', description: 'Government policies and interventions for development in various sectors and issues arising out of their design and implementation. Development processes and the development industry —the role of NGOs, SHGs, various groups and associations, donors, charities, institutional and other stakeholders. Welfare schemes for vulnerable sections of the population by the Centre and States and the performance of these schemes; mechanisms, laws, institutions and Bodies constituted for the protection and betterment of these vulnerable sections. Issues relating to development and management of Social Sector/Services relating to Health, Education, Human Resources. Issues relating to poverty and hunger.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs2-ir', title: 'International Relations', description: 'India and its neighborhood - relations. Bilateral, regional and global groupings and agreements involving India and/or affecting India’s interests. Effect of policies and politics of developed and developing countries on India’s interests, Indian diaspora. Important International institutions, agencies and fora- their structure, mandate.', tags: [], mastery: 'none', resources: [] },
        ]
      },
      {
        id: 'mains-gs3',
        title: 'Paper IV: General Studies III',
        icon: 'FileText',
        description: 'Technology, Economic Development, Bio diversity, Environment, Security and Disaster Management. Marks: 250.',
        tags: ['gs-3', 'economy', 'sci-tech', 'security'],
        mastery: 'none',
        resources: [],
        subtopics: [
          { id: 'mains-gs3-economy', title: 'Economic Development', description: 'Indian Economy and issues relating to planning, mobilization, of resources, growth, development and employment. Inclusive growth and issues arising from it. Government Budgeting. Effects of liberalization on the economy, changes in industrial policy and their effects on industrial growth. Infrastructure: Energy, Ports, Roads, Airports, Railways etc. Investment models.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs3-agriculture', title: 'Agriculture', description: 'Major crops-cropping patterns in various parts of the country, - different types of irrigation and irrigation systems storage, transport and marketing of agricultural produce and issues and related constraints; e-technology in the aid of farmers. Issues related to direct and indirect farm subsidies and minimum support prices; Public Distribution System- objectives, functioning, limitations, revamping; issues of buffer stocks and food security; Technology missions; economics of animal-rearing. Food processing and related industries in India- scope’ and significance, location, upstream and downstream requirements, supply chain management. Land reforms in India.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs3-scitech', title: 'Science & Technology', description: 'Developments and their applications and effects in everyday life. Achievements of Indians in science & technology; indigenization of technology and developing new technology. Awareness in the fields of IT, Space, Computers, robotics, nano-technology, bio-technology and issues relating to intellectual property rights.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs3-environment', title: 'Environment & Biodiversity', description: 'Conservation, environmental pollution and degradation, environmental impact assessment.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs3-dm', title: 'Disaster Management', description: 'Disaster and disaster management.', tags: [], mastery: 'none', resources: [] },
          { id: 'mains-gs3-security', title: 'Internal Security', description: 'Linkages between development and spread of extremism. Role of external state and non-state actors in creating challenges to internal security. Challenges to internal security through communication networks, role of media and social networking sites in internal security challenges, basics of cyber security; money-laundering and its prevention. Security challenges and their management in border areas - linkages of organized crime with terrorism. Various Security forces and agencies and their mandate.', tags: [], mastery: 'none', resources: [] },
        ]
      },
      {
        id: 'mains-gs4',
        title: 'Paper V: General Studies IV',
        icon: 'FileText',
        description: 'Ethics, Integrity, and Aptitude. This paper will include questions to test the candidates’ attitude and approach to issues relating to integrity, probity in public life and his problem-solving approach to various issues and conflicts faced by him in dealing with society. Questions may utilise the case study approach. Marks: 250.',
        tags: ['gs-4', 'ethics', 'aptitude'],
        mastery: 'none',
        resources: [],
        subtopics: [
            { id: 'mains-gs4-ethics-interface', title: 'Ethics and Human Interface', description: 'Essence, determinants and consequences of Ethics in-human actions; dimensions of ethics; ethics - in private and public relationships. Human Values - lessons from the lives and teachings of great leaders, reformers and administrators; role of family, society and educational institutions in inculcating values.', tags: [], mastery: 'none', resources: []},
            { id: 'mains-gs4-attitude', title: 'Attitude', description: 'Content, structure, function; its influence and relation with thought and behavior; moral and political attitudes; social influence and persuasion.', tags: [], mastery: 'none', resources: []},
            { id: 'mains-gs4-aptitude', title: 'Aptitude and Foundational Values for Civil Service', description: 'Integrity, impartiality and non-partisanship, objectivity, dedication to public service, empathy, tolerance and compassion towards the weaker-sections.', tags: [], mastery: 'none', resources: []},
            { id: 'mains-gs4-ei', title: 'Emotional Intelligence', description: 'Concepts, and their utilities and application in administration and governance.', tags: [], mastery: 'none', resources: []},
            { id: 'mains-gs4-thinkers', title: 'Contributions of moral thinkers and philosophers from India and world.', description: 'Contributions from Indian and World thinkers like Gandhi, Kant, Aristotle, etc.', tags: [], mastery: 'none', resources: []},
            { id: 'mains-gs4-public-service', title: 'Public/Civil service values and Ethics in Public administration', description: 'Status and problems; ethical concerns and dilemmas in government and private institutions; laws, rules, regulations and conscience as sources of ethical guidance; accountability and ethical governance; strengthening of ethical and moral values in governance; ethical issues in international relations and funding; corporate governance.', tags: [], mastery: 'none', resources: []},
            { id: 'mains-gs4-probity', title: 'Probity in Governance', description: 'Concept of public service; Philosophical basis of governance and probity; Information sharing and transparency in government, Right to Information, Codes of Ethics, Codes of Conduct, Citizen’s Charters, Work culture, Quality of service delivery, Utilization of public funds, challenges of corruption.', tags: [], mastery: 'none', resources: []},
            { id: 'mains-gs4-casestudies', title: 'Case Studies on above issues.', description: 'Analysis of realistic or hypothetical scenarios to test ethical decision-making.', tags: [], mastery: 'none', resources: []},
        ]
      },
      {
        id: 'mains-optional',
        title: 'Papers VI & VII: Optional Subject',
        icon: 'BookMarked',
        description: 'Candidates choose one subject from a list for two papers. This tests in-depth, graduate-level knowledge of the chosen discipline.',
        tags: ['optional', 'specialized', 'merit'],
        mastery: 'none',
        resources: [],
        subtopics: [
          {
            id: 'psychology-optional',
            title: 'Psychology Optional',
            description: 'Covers theoretical and applied psychology. Paper I focuses on foundations, and Paper II on issues and applications.',
            tags: ['psychology', 'optional-subject'],
            mastery: 'none',
            resources: [],
            subtopics: [
              {
                id: 'psych-p1',
                title: 'Paper I: Foundations of Psychology',
                description: 'Covers the fundamental principles and theories of psychology.',
                tags: [],
                mastery: 'none',
                resources: [],
                subtopics: [
                  { id: 'psych-p1-1', title: '1. Introduction', description: 'Definition; Historical antecedents & trends; Psychology & scientific methods; Relation to other sciences; Application to societal problems.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-2', title: '2. Methods of Psychology', description: 'Types of research; Methods (Survey, observation, case-study, experiments); Experimental & non-experimental designs; Qualitative techniques.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-3', title: '3. Research Methods', description: 'Steps in research; Data collection methods; Statistical applications (t-test, ANOVA, correlation, regression, factor analysis).', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-4', title: '4. Development of Human Behaviour', description: 'Growth & development principles; Role of genetic & environmental factors; Life span development stages & well-being.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-5', title: '5. Sensation, Attention and Perception', description: 'Threshold concepts; Signal detection; Factors influencing attention; Perceptual organization; ESP; Culture & perception.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-6', title: '6. Learning', description: 'Theories (Behaviourist, Gestalt, Info-processing); Processes (extinction, discrimination); Reinforcement schedules; Social learning.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-7', title: '7. Memory', description: 'Encoding & remembering; STM, LTM, Sensory memory; Levels of processing; Forgetting theories; Amnesia.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-8', title: '8. Thinking and Problem Solving', description: 'Piaget’s theory; Concept formation; Reasoning; Problem-solving methods; Creativity; Decision making.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-9', title: '9. Motivation and Emotion', description: 'Psychological & physiological basis; Measurement; Effects on behaviour; Intrinsic & extrinsic motivation; Emotional competence.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-10', title: '10. Intelligence and Aptitude', description: 'Theories (Spearman, Thurstone, etc.); Emotional & social intelligence; IQ measurement; Multiple intelligences.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-11', title: '11. Personality', description: 'Theories (psychoanalytical, trait, humanistic, etc.); Measurement (projective tests); Indian approach; Big 5 factor theory.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-12', title: '12. Attitudes, Values and Interests', description: 'Components & formation of attitudes; Measurement; Attitude change theories; Stereotypes & prejudices.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-13', title: '13. Language and Communication', description: 'Language properties & acquisition (Skinner, Chomsky); Communication process & types; Effective communication training.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p1-14', title: '14. Issues and Perspectives in Modern Psychology', description: 'Computer application & AI; Consciousness studies (sleep, dreams, meditation); ESP; Simulation studies.', tags: [], mastery: 'none', resources: [] },
                ]
              },
              {
                id: 'psych-p2',
                title: 'Paper II: Psychology: Issues and Applications',
                description: 'Focuses on the practical application of psychological principles.',
                tags: [],
                mastery: 'none',
                resources: [],
                subtopics: [
                  { id: 'psych-p2-1', title: '1. Psychological Measurement of Individual Differences', description: 'Nature of individual differences; Construction & use of standardized tests; Ethical issues.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-2', title: '2. Psychological well-being and Mental Disorders', description: 'Concept of health/ill-health; Causal factors in mental disorders; Positive health & well-being.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-3', title: '3. Therapeutic Approaches', description: 'Psychodynamic, behaviour, client-centered, cognitive therapies; Indigenous therapies (Yoga, Meditation); Rehabilitation.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-4', title: '4. Work Psychology and Organisational Behaviour', description: 'Personnel selection & training; Work motivation theories; Leadership; Stress management; Consumer psychology.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-5', title: '5. Application to Educational Field', description: 'Teaching-learning process; Training for special needs; Guidance & counseling; Psychological tests in education.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-6', title: '6. Community Psychology', description: 'Concept & use in social action; Arousing community consciousness; Leadership for social change.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-7', title: '7. Rehabilitation Psychology', description: 'Prevention programs; Rehabilitation for physically, mentally, socially challenged persons; Victims of violence/substance abuse.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-8', title: '8. Application to disadvantaged groups', description: 'Concepts of deprivation; Consequences; Educating & motivating the disadvantaged.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-9', title: '9. Psychological problem of social integration', description: 'Problem of caste, class, religion conflicts; Prejudice nature & causes; Strategies for handling conflicts.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-10', title: '10. Application in IT and Mass Media', description: 'Role of psychologists in IT/media; Distance learning; E-commerce; Impact of TV & social media.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-11', title: '11. Psychology and Economic development', description: 'Achievement motivation; Entrepreneurial behaviour; Motivating for entrepreneurship; Consumer rights.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-12', title: '12. Application to environment and related fields', description: 'Environmental psychology; Effects of noise, pollution, crowding; Population psychology; Motivating for small family norms.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-13', title: '13. Application of psychology in other fields', description: 'Military Psychology, Sports Psychology, Media influences, Psychology of Terrorism.', tags: [], mastery: 'none', resources: [] },
                  { id: 'psych-p2-14', title: '14. Psychology of Gender', description: 'Issues of discrimination, Management of diversity, Glass ceiling effect, Women and Indian society.', tags: [], mastery: 'none', resources: [] },
                ]
              }
            ]
          },
        ],
      },
    ],
  },
  {
    id: 'interview',
    title: 'Stage III: Personality Test / Interview',
    icon: 'Users',
    description: 'The final stage to assess suitability for a career in public service. It evaluates mental alertness, critical thinking, leadership, and integrity. Total marks: 275.',
    tags: ['interview', 'personality-test', 'final-stage'],
    mastery: 'none',
    resources: [],
    subtopics: [
      {
        id: 'interview-qualities',
        title: 'Qualities Judged',
        icon: 'HelpCircle',
        description: 'Mental alertness, critical powers of assimilation, clear and logical exposition, balance of judgment, leadership abilities, ability for social cohesion, intellectual and moral integrity.',
        tags: ['evaluation-criteria'],
        mastery: 'none',
        resources: [],
      }
    ]
  },
];

    